name: Node.js CI - with no cache

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: run build
      working-directory: app/
      run: |
        npm ci
        npm run build --if-present
