name: Node.js CI - different engines

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 18]

    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Restore Cache
      id: cache
      uses: actions/cache/restore@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ matrix.node }}
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: run build
      working-directory: app/
      run: |
        npm ci
        npm run build --if-present
    - name: Save Cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/upload-artifact@v4
      with:
        name: my-app-${{ matrix.os }}-${{ matrix.node }}
        path: app/dist/
        retention-days: 1

  deploy-job:
    needs: [ build ]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 18]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-app-${{ matrix.os }}-${{ matrix.node }}
          path: downloaded-content
      - run: |
          ls downloaded-content
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: my-app-${{ matrix.os }}-${{ matrix.node }}
