name: Test Deployment

on:
   pull_request:
   push:

jobs:  
    dev-job:
      environment: Dev
      runs-on: ubuntu-latest
      steps:
        - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY
